# Generated by Django 4.2.6 on 2023-10-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['parent__pk']},
        ),
    ]
